[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "web-hacker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openai>=2.6.1",
    "python-dotenv>=1.2.1",
    "websocket-client>=1.6.0",
    "requests>=2.31.0",
]

[tool.hatch.build.targets.wheel]
packages = ["src"]
